-- Read only: resolve original Archer field names from SSP.
-- Replace only the three SET values with your table names.
SET DIM_TABLE = '<CURATED_DB>.<CURATED_SCHEMA>.<SSP_DIM>';
SET FACT_TABLE = '<CURATED_DB>.<CURATED_SCHEMA>.<SSP_FACT>';
SET ARCHER_FIELDS_TABLE = '<RAW_DB>.<RAW_SCHEMA>.<ARCHER_META_FIELD>';

-- 1. System Implementation: exact original field name from lineage.
SELECT DISTINCT
    p.METADATA_JSON:"value"::STRING AS ARCHER_SQL_FIELD_NAME,
    c.METADATA_JSON:"type"::STRING AS COMPONENT_TYPE
FROM IDENTIFIER($DIM_TABLE) c
JOIN IDENTIFIER($FACT_TABLE) f
  ON f.FK_SOURCE_ELEMENT_HASH = c.PK_OSCAL_SSP_ELEMENT_HASH
 AND f.DEPENDENCY_TYPE = 'CONTAINS'
JOIN IDENTIFIER($DIM_TABLE) p
  ON p.PK_OSCAL_SSP_ELEMENT_HASH = f.FK_TARGET_ELEMENT_HASH
WHERE c.ELEMENT_TYPE = 'components'
  AND p.ELEMENT_TYPE = 'props'
  AND p.METADATA_JSON:"name"::STRING = 'source-field'
ORDER BY ARCHER_SQL_FIELD_NAME, COMPONENT_TYPE;

-- 2. Business props under System Characteristics: Archer metadata candidates.
-- If more than one Field ID/Level ID appears, review the source LevelId.
-- The approved mapping CSV is authoritative for SOURCE_FIELD_NAME -> OSCAL path.
SELECT DISTINCT
    p.METADATA_JSON:"name"::STRING AS OSCAL_PROPERTY_NAME,
    m.SQL_FIELD_NAME AS ARCHER_SQL_FIELD_NAME,
    m.FIELD_NAME AS ARCHER_DISPLAY_NAME,
    m.FIELD_ID AS ARCHER_FIELD_ID,
    m.LEVEL_ID AS ARCHER_LEVEL_ID
FROM IDENTIFIER($DIM_TABLE) sc
JOIN IDENTIFIER($FACT_TABLE) f
  ON f.FK_SOURCE_ELEMENT_HASH = sc.PK_OSCAL_SSP_ELEMENT_HASH
 AND f.DEPENDENCY_TYPE = 'CONTAINS'
JOIN IDENTIFIER($DIM_TABLE) p
  ON p.PK_OSCAL_SSP_ELEMENT_HASH = f.FK_TARGET_ELEMENT_HASH
LEFT JOIN IDENTIFIER($ARCHER_FIELDS_TABLE) m
  ON REGEXP_REPLACE(LOWER(m.SQL_FIELD_NAME), '[^a-z0-9]+', '-') =
     p.METADATA_JSON:"name"::STRING
WHERE sc.ELEMENT_TYPE = 'system-characteristics'
  AND p.ELEMENT_TYPE = 'props'
  AND p.METADATA_JSON:"name"::STRING <> 'source-field'
ORDER BY OSCAL_PROPERTY_NAME, ARCHER_SQL_FIELD_NAME, ARCHER_LEVEL_ID;
