-- Read-only: show one mapped SSP property.
-- Replace only <CURATED_DATABASE>.<CURATED_SCHEMA> with your Snowflake values.
SELECT
    SOURCE_RECORD_ID,
    METADATA_JSON:"name"::STRING AS PROPERTY_NAME,
    METADATA_JSON:"value" AS PROPERTY_VALUE
FROM <CURATED_DATABASE>.<CURATED_SCHEMA>.DIM_OSCAL_SSP_ELEMENT
WHERE ELEMENT_TYPE = 'props'
  AND METADATA_JSON:"name"::STRING = 'allocated-controls'
LIMIT 20;
